apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
    version: 2.0.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer